[package]
name = "migration"
version = "0.1.0"
authors = ["Eqoty Labs"]
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
serde-cw-value = { version = "0.7.0" }
serde = { version = "1.0.152", default-features = false, features = ["derive"] }
serde_repr = "0.1.10"
schemars = "0.8.11"
cosmwasm-std = { package = "secret-cosmwasm-std", version = "1.0.0", default-features = false }
secret-toolkit = { version = "0.7.0", default-features = false, features = ["viewing-key"] }
