[workspace]
members = ["contracts/*"]
resolver = "2"


[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[workspace.dependencies]
snip721-reference-impl = { git = "https://github.com/eqoty-labs/snip721-reference-impl", rev = "5ae22b4" }
cosmwasm-contract-migratable-std = { git = "https://github.com/eqoty-labs/cosmwasm-contract-migratable-std", tag = "v2.1.0" }
serde = { version = "1.0.158", default-features = false, features = ["derive"] }
