use cosmwasm_std::{Addr, Binary, Storage};
use cosmwasm_storage::{ReadonlySingleton, singleton, Singleton, singleton_read};
use serde::{Deserialize, Serialize};
use snip721_reference_impl::token::Metadata;


pub static CONFIG_KEY: &[u8] = b"config";
/// storage key for allowed Coin prices for purchasing a mint: Vec<Coin>
pub const PURCHASE_PRICES_KEY: &[u8] = b"prices";
/// storage key for the PurchasableMetadata used for every purchased mint
pub const PURCHASABLE_METADATA_KEY: &[u8] = b"pur_metadata";
/// storage key for current ContractMode
pub const CONTRACT_MODE_KEY: &[u8] = b"pur_contract_mode";

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct PurchasableMetadata {
    /// optional public metadata that can be seen by everyone
    pub public_metadata: Option<Metadata>,
    /// optional private metadata that can only be seen by the owner and whitelist
    pub private_metadata: Option<Metadata>,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct State {
    /// When in ContractMode.MigrateDataIn, it will hold the address being migrated from
    /// When in ContractMode.Running, it will be None
    /// When in ContractMode.MigratedOut, it will hold the address the contract migrated to
    pub migration_addr: Option<Addr>,
    /// When in ContractMode.MigrateDataIn, it will hold the code hash of the contract being migrated from
    /// When in ContractMode.Running, it will be None
    /// When in ContractMode.MigratedOut, it will hold the code hash of the contract that was migrated to
    pub migration_code_hash: Option<String>,
    /// When in ContractMode.MigrateDataIn, it will hold the secret generated by the contract being migrated from
    /// When in ContractMode.Running, it will be None
    /// When in ContractMode.MigratedOut, it will hold the secret needed by another contract to migrate data out
    pub migration_secret: Option<Binary>,
    /// the mint_cnt of the contract being migrated from
    pub migrate_in_mint_cnt: Option<u32>,
    /// the next mint index out of migrate_in_mint_cnt that must be migrated
    pub migrate_in_next_mint_index: Option<u32>,
}

#[derive(serde_repr::Serialize_repr, serde_repr::Deserialize_repr)]
#[repr(u8)]
pub enum ContractMode {
    MigrateDataIn = 1,
    Running = 2,
    MigratedOut = 3,
}

pub fn config(storage: &mut dyn Storage) -> Singleton<State> {
    singleton(storage, CONFIG_KEY)
}

pub fn config_read(storage: &dyn Storage) -> ReadonlySingleton<State> {
    singleton_read(storage, CONFIG_KEY)
}
